# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chats.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hats.proto\x12\x0bllm_chat_v1\"!\n\x13StartSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x14StartSessionResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2d\n\x0eLLMChatService\x12R\n\x0bProcessText\x12 .llm_chat_v1.StartSessionRequest\x1a!.llm_chat_v1.StartSessionResponseB5Z3../backend/grpc/gen/service/llm_chat/v1;llm_chat_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3../backend/grpc/gen/service/llm_chat/v1;llm_chat_v1'
  _globals['_STARTSESSIONREQUEST']._serialized_start=28
  _globals['_STARTSESSIONREQUEST']._serialized_end=61
  _globals['_STARTSESSIONRESPONSE']._serialized_start=63
  _globals['_STARTSESSIONRESPONSE']._serialized_end=98
  _globals['_LLMCHATSERVICE']._serialized_start=100
  _globals['_LLMCHATSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
