version: '3'

services:
  nextjs:
    build:
      context: ./frontend/simple-yaub
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    restart: unless-stopped
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    volumes:
      - ${SECRETS_LETSENCRYPT}:/etc/letsencrypt:ro
      - ${SECRETS_CERTBOT_DATA}:/var/www/certbot
#  certbot:
#    container_name: certbot
#    image: certbot/certbot:latest
#    depends_on:
#      - nginx
#    volumes:
#      - ${SECRETS_LETSENCRYPT}:/etc/letsencrypt
#      - ${SECRETS_CERTBOT_DATA}:/var/www/certbot
#    command: >-
#      certonly --reinstall --webroot --webroot-path=/var/www/certbot
#      --email ${EMAIL} --agree-tos --no-eff-email
#      -d yablog.duckdns.org
