[tool.poetry]
name = "llmer"
version = "0.1.0"
description = "Connector for LLMs"
authors = ["freelectron"]
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"